ToDoWeb/Controllers/GoalController.cs
using DataLayer.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace ToDoWeb.Controllers
{
    public class GoalController : Controller
    {
        private readonly ILogger<GoalController> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public GoalController(ILogger<GoalController> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {

            IEnumerable<Goal> goalsList = _unitOfWork.Goal.GetAll();
            return View(goalsList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Goal obj)
        {
            _unitOfWork.Goal.Add(obj);
            _unitOfWork.Save();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Update(int? id)
        {
            if (id == 0 || id == null) return NotFound();

            Goal? goalFromDb = _unitOfWork.Goal.Get(c => c.Id == id);
            return View(goalFromDb);
        }

        [HttpPost]
        public IActionResult Update(Goal goal)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Goal.Update(goal);
                _unitOfWork.Save();
                TempData["success"] = "Goal edited successfully";
                return RedirectToAction("Index", "Home");
            }
            return View(goal);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0) return NotFound();

            Goal? goal = _unitOfWork.Goal.Get(c => c.Id == id);
            if (goal == null) return NotFound();

            return View(goal);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Goal? goal = _unitOfWork.Goal.Get(c => c.Id == id);
            if (goal == null)
            {
                return NotFound();
            }
            _unitOfWork.Goal.Remove(goal);
            _unitOfWork.Save();
            TempData["success"] = "Goal deleted successfully";
            return RedirectToAction("Index", "Home");
        }


        public IActionResult Privacy()
        {
            return View();
        }
    }
}

ToDoWeb/Controllers/HomeController.cs
using DataLayer.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Models;
using System.Diagnostics;
using System.Security.Claims;

namespace SimpleToDo
{
    //[Area("Customer")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public HomeController(ILogger<HomeController> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {

            IEnumerable<Goal> goalsList = _unitOfWork.Goal.GetAll();
            return View(goalsList);
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

ToDoWeb/Views/Home/Index.cshtml
@model IEnumerable<Goal>

<div class="container">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">Goals</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Goal" asp-action="Create" class="btn btn-primary">
            <i class="bi bi-plus-circle"> Create New Goal</i>
            </a>
        </div>
    </div>
</div>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Status</th>
            <th>User</th>
            <th>Goal</th>
            <th>End Date</th>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td>
                    @if (@obj.Completed)
                    {
                        <i class="bi bi-check2-square"></i>
                    }
                    else
                    {
                        <i class="bi bi-x-square"></i>
                    }
                </td>
                <td>@obj.UserId</td>
                <td>@obj.Name</td>
                <td>@obj.EndDay</td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Goal" asp-action="Update" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                            <i class="bi bi-pencil-square">Edit</i>
                        </a>
                        <a asp-controller="Goal" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                            <i class="bi bi-trash-fill"></i>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>